# Server settings
server:
    port:8080
    address:localhost

# DATASOURCE
jdbc:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&charaterEncoding=utf-8
    databaseName: test
    serverName: 127.0.0.1
    username: root
    password: root
    cachePrepStmts: true
    prepStmtsSize: 250
    prepStmtsCacheSqlLimit: 2048
    userServerPrepStmts: true

# SPRING PROFILES
spring:
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true

# MyBatis
mybatis:
    typeAliasesPackage: com.tony.entity
    mapperLocations: classpath:/com/tony/mapper/*.xml
    configLocation: classpath:/mybatis-config.xml

# LOGGING
logging:
    level:
       com.ibatis:DEBUG