spring:
  profiles:
    active: dev     # 本地环境
#    active: dev       # 环境
#    active: test      # 开发测试环境
#    active: pre       # 预发环境
#    active: online    # 生产环境

# health monitor
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@spring.boot.version@"

logging:
  config: classpath:logback-baili.xml
#  level: INFO