server:
  port: 8081

rocketmq:
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: bailitest
    #mq的nameserver地址
    namesrvAddr: localhost:9876
    #如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
    instanceName: bailiProducer
    #topic名称
    topic: TEST
    #根据实际情况设置消息的tag
    tag: first
    #消息最大长度
    maxMessageSize: 131072 # 1024*128
    #发送消息超时时间
    sendMsgTimeout: 10000
  consumer:
    namesrvAddr: localhost:9876
    groupName: bailitest
    topic: TEST
    tag: first
    consumeThreadMin: 20
    consumeThreadMax: 64

spring:
  application:
      name: springboot-study
  #quartz
  quartz:
    enabled: true
  # MySQL
  datasource:
      url: jdbc:mysql://47.94.14.194:3306/baili?useUnicode=true&characterEncoding=utf8
      #url: jdbc:mysql://localhost:3306/baili?useSSL=true&useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

      #连接池的配置信息
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      # Druid Login Params
      loginUserName: admin
      loginPassword: Hello@1234
  # REDIS
  redis:
      host: 47.94.14.194 # server host
      port: 6399 # connection port
      database: 2 # database name
      password: baili # server password
      timeout: 2000
      # 默认缓存过期时间（秒）
      expireSeconds: 3600
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1


  # Dubbo
  dubbo:
    #scan: com.mhc.venucia.core.dubbo.service
    application:
      name: springboot-study
      owner: baili
      organization: baili
    registry:
      address: zookeeper://47.94.14.194:2181
    protocol:
      name: dubbo
      port: 20880
    provider:
      version: 1.0_baili_local
      timeout: 60000
    consumer:
      version: 1.0_baili_local
      timeout: 60000
      retries: 0
      check: false

  # Logback
  log:
    file:
      path: ${HOME}/logs/${spring.application.name}/${spring.profiles.active} # 日志文件路径
      maxKeep: 5  # 最大保留的文件个数
  mail:
    host: smtp.163.com
    username: jiangjingmingjava@163.com
    password: AS158...
    properties:
      mail:
        smtp:
          anth: true
          starttls:
            enable: true
            required: true
  # ES
  data:
    elasticsearch:
      # 集群名
      cluster-name: elasticsearch
      # 连接节点,注意在集群中通信都是9300端口，否则会报错无法连接上！
      cluster-nodes: localhost:9300
      # 是否本地连接
      local: false
      repositories:
        # 仓库中数据存储
        enabled: true